Ajenti bug report
--------------------


Info | Value
----- | -----
Ajenti | 2.1.17
Platform | debian / ubuntu / Ubuntu 16.04.3 LTS
Architecture | x86_64 x86_64
Python | 2.7.12
Debug | True
Loaded plugins | 

Library | Version
------- | -------
gevent | 1.2.2
greenlet | 0.4.12
psutil | 5.4.0


    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/aj/entry.py", line 52, in handle_crash
        report = open(report_path, 'w')
    IOError: [Errno 13] Permission denied: '/root/ajenti-crash.txt'

            